name: testing, building
on: 
  push:
    branches: [master]
  pull_request:
    branches: [maser]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [17.x]
    steps:
      - uses: actions/checkout@v2
        name: Staring Node.js ${{matrix.node_version}}
      - uses: actions/setup-node@v1
        with:
          node_version: ${{matrix.node_version}}
      - name: install modules
        run: npm install
      - name: build production project      
        run: npm run build:prod
      - name: testing       
        run: npm run test:unit  