name: pipeline
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: macos-13
    strategy:
      matrix:
        node_version: [20.5.0]
    steps:
      - uses: actions/checkout@v3
        name: Staring Node.js ${{matrix.node_version}}
      - uses: actions/setup-node@v3
        with:
          node_version: ${{matrix.node_version}}
      - name: install modules
        run: npm install
      - name: build production project      
        run: npm run build:prod          
      - name: testing       
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        run: npm run test:ui:ci
